input {
  http {
    port => 8080
    codec => json {
      target => "app"
    }
  }

  gelf {
    port => 12201
  }
}

filter {
  if [short_message] {
    json {
      source => "short_message"
      target => "app"
      skip_on_invalid_json => true
    }
  }

  if [app][time] {
    date {
      match => ["[app][time]", "ISO8601"]
      target => "@timestamp"
    }
  }

  mutate {
    add_field => {
      "service" => "github-release-notifier"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "github-release-notifier-logs-%{+YYYY.MM.dd}"
  }
}
